### ISSUE TITLE
Results on COCO 2017 dataset

### ISSUE THREAD

**Issue by aiotko** [microsoft/GLIP#11]
Hi,

Could you please clarify what is your actual results on coco 2017 dataset?

I've just found the submission from GLIP/Microsoft research team that took the 2nd place on coco test-dev2019 with AP=0.62 and AP50=0.80 

Have you used GLIP-L model or another one which is not public so far?

https://competitions.codalab.org/competitions/20794#results

**Comment by aiotko** [comment]
Hi, 

Sorry, I've investigated the point a bit more, tried out GLIP-L model with the proposed weights and got 51.2% AP on val2017 dataset.

**Comment by MarcusNerva** [comment]
@aiotko Hi there! May I ask how do you perform object detection on coco 2017? Given a image, do you join the 80 class name together with '.', then input this prompt with this image into the GLIP model?

**Comment by aiotko** [comment]
@MarcusNerva yep, I joined all 80 classes via '.'

Please find the source code for object detection in the PR, I've just adapted the [colab Demo](https://colab.research.google.com/drive/12x7v-_miN7-SRiziK3Cx4ffJzstBJNqb?usp=sharing) for running on a local image a bit. 

https://github.com/microsoft/GLIP/pull/14/files

**Comment by liunian-harold-li** [comment]
Hi, sorry for the late reply. The released GLIP-L is not tuned on COCO so the 51.X AP is the zero-shot AP. I will check whether I could find the fine-tuned GLIP-L checkpoint. I do not have access to the stored weights on the servers right now so that could take some time.

For the 0.62 mAP model on the leaderboard, yes it is a new GLIP model and we will release the paper soon!
