### ISSUE TITLE
The noun phrase extraction algorithm

### ISSUE THREAD

**Issue by tgxs002** [microsoft/GLIP#18]
Hi,

I am interested in the noun phrase extraction algorithm, but it seems this process is not very detailed in the GLIP paper and code. Is more details about it available? 

Thanks,
Blakey

**Comment by Haotian-Zhang** [comment]
Hi @tgxs002, thank you for your questions. The noun phrase extraction algorithm (Named Entity Recognition) is not our focus in the paper, and we are only applying it to extract the positive phrases (character span) in the whole sentence from our caption data (since the positive character span in GoldG from our training data, MDETR has already extracted for us. ). The code pieces used in our repo can be referred to: 

https://github.com/microsoft/GLIP/blob/fd52c6361f013e70ae7682d90b3ab3ca2bd5e6bc/maskrcnn_benchmark/engine/predictor_glip.py#L107-L127. 

For more more details, please visit the official NLTK page.

**Comment by tgxs002** [comment]
Thank you for your timely response!
