### ISSUE TITLE
TypeError: CheckpointFunctionBackward.forward: expected Tensor or tuple of Tensor (got NoneType) for return value 6

### ISSUE THREAD

**Issue by Edwardmark** [microsoft/GLIP#3]
When I run the test code on coco benchmark, following error shows:
TypeError: CheckpointFunctionBackward.forward: expected Tensor or tuple of Tensor (got NoneType) for return value 6

**Comment by liunian-harold-li** [comment]
Hi, could you check your PyTorch version? This error might be due to the checkpoint api is different on older version of PyTorch https://pytorch.org/docs/stable/checkpoint.html.

Otherwise, if you are only interested in the test code on COCO, could you append this parameter to the command line to disable checkpoint and see if the issue could be resolved?

MODEL.DYHEAD.USE_CHECKPOINT False

**Comment by Edwardmark** [comment]
> Hi, could you check your PyTorch version? This error might be due to the checkpoint api is different on older version of PyTorch https://pytorch.org/docs/stable/checkpoint.html.
> 
> Otherwise, if you are only interested in the test code on COCO, could you append this parameter to the command line to disable checkpoint and see if the issue could be resolved?
> 
> MODEL.DYHEAD.USE_CHECKPOINT False

hi what version should I use for this code? I am using pytorch 1.8.0. Thanks

**Comment by Edwardmark** [comment]
@liunian-harold-li could you please give out a requirements.txt or a dockerfile so everybody can reproduce the result easily.
Thanks.

**Comment by Edwardmark** [comment]
@liunian-harold-li I change the pytorch to 1.10.0， then it works, thanks.
