### ISSUE TITLE
no box detected using code in the codelab demo

### ISSUE THREAD

**Issue by abril4416** [microsoft/GLIP#31]
Thanks for the great work! I'm trying the code provided in your codelab demo. However,  there is no bounding box detected (No errors appear during the compiling and execution). I've also tried to re-install packages to ensure versions of packages on my server are the same as those in your code. Is there any possible reasons for the result?
![image](https://user-images.githubusercontent.com/31852492/180903892-fae7a884-c641-4972-86ac-2da73ba713f9.png)
![image](https://user-images.githubusercontent.com/31852492/180903943-98d8f0ff-5224-4b5b-aefe-4065be63f218.png)

**Comment by Haotian-Zhang** [comment]
@abril4416 Hi, thank you for the support! Due to the recent update of the Colab env (CUDA and Pytorch version), our original code does not seem compatible. There are mainly two quick fixes that need to be added to the notebook and to the codes to make the demo work.

1. In the Colab demo: 'cuda' needs to be changed with 'cuda-10.2'
<img width="1310" alt="image" src="https://user-images.githubusercontent.com/28856987/180913401-b0fcf240-c076-4659-a372-78dd583bcecf.png">
After installing the cuda-10.2, it's always better to double-check the CUDA installation with '!nvcc -V'. 

2. In the codes (maskrcnn_benchmark/engine/predictor_glip.py) https://github.com/microsoft/GLIP/blob/fd52c6361f013e70ae7682d90b3ab3ca2bd5e6bc/maskrcnn_benchmark/engine/predictor_glip.py#L347, please change the self.color to 255. 
<img width="583" alt="image" src="https://user-images.githubusercontent.com/28856987/180914143-60f6681c-e1ab-4738-a0f5-5081bb68733d.png">

Sorry I am currently busy with something else, so I don't have time to update the codes. We will make sure to fix the issues and release them with the updated GLIPv2 codes and models very soon. Thanks for the support and patience!

**Comment by abril4416** [comment]
Hi haotian, thanks for the patient reply. I'll try the updated codes as you've mentioned first. A problem is that I re-use the code on my own server, but there is no bounding box detected (no errors appeared). Could you please offer some suggestions when you are free?

> @abril4416 Hi, thank you for the support! Due to the recent update of the Colab env (CUDA and Pytorch version), our original code does not seem compatible. There are mainly two quick fixes that need to be added to the notebook and to the codes to make the demo work.
> 
> 1. In the Colab demo: 'cuda' needs to be changed with 'cuda-10.2'
> 
> <img alt="image" width="1310" src="https://user-images.githubusercontent.com/28856987/180913401-b0fcf240-c076-4659-a372-78dd583bcecf.png">
> 
> After installing the cuda-10.2, it's always better to double-check the CUDA installation with '!nvcc -V'.
> 2. In the codes (maskrcnn_benchmark/engine/predictor_glip.py) https://github.com/microsoft/GLIP/blob/fd52c6361f013e70ae7682d90b3ab3ca2bd5e6bc/maskrcnn_benchmark/engine/predictor_glip.py#L347
>    , please change the self.color to 255.
> 
> <img alt="image" width="583" src="https://user-images.githubusercontent.com/28856987/180914143-60f6681c-e1ab-4738-a0f5-5081bb68733d.png">
> 
> Sorry I am currently busy with something else, so I don't have time to update the codes. We will make sure to fix the issues and release them with the updated GLIPv2 codes and models very soon. Thanks for the support and patience!

**Comment by ktrapeznikov** [comment]
@abril4416  did you ever solve your problem?

**Comment by liunian-harold-li** [comment]
Hi, I have updated the demo to use an older version of the code for
inference. Could you try again to see if your problem persists?

**Comment by MrWaterZhou** [comment]
no need to change the code.
just add
`glip_demo.color = 255`
after initialize "GLIPDemo" class

**Comment by norbertgerena** [comment]
If after specifying the self.color, it still does not work. Make sure to check if the bboxlist contains non-zero `num_boxes`
`result, bboxlist = glip_demo.run_on_web_image(image, caption, 0.5)`

bboxlist:
`BoxList(num_boxes=2, image_width=640, image_height=480, mode=xyxy)`
`num_boxes`, should greater than zero.

If it's zero, consider checking if you have downloaded the right weights for your config yaml file. For example, these 2 are different set of weights:

https://huggingface.co/GLIPModel/GLIP/resolve/main/glip_tiny_model_o365_goldg.pth
https://huggingface.co/GLIPModel/GLIP/resolve/main/glip_a_tiny_o365.pth
