### ISSUE TITLE
Some questions about the paper GLIP_v1

### ISSUE THREAD

**Issue by SKBL5694** [microsoft/GLIP#47]
In the appendix C.1. Pre-training Details: you say "with a probability of 0.5, we uniformly choose an integer N from [1,85 - |Cpos|] and put N categories in the prompt".
What's the meaning of [1,85 - |Cpos|], and how to deal with the probability of 0.5? I can understand how to get N? Can you explain it in more detail？

**Comment by liunian-harold-li** [comment]
Thank you for the question! We always keep all the positive categories in the prompt. Then:

Half of the time, we will add negative categories to the prompt till we have 85 categories in the prompt in total (including both the positive and negative ones);

Half of the time, we want to add less negative categories (this is because we want the model to be exposed to prompts with varying lengths). Thus, we will randomly decide how many negative categories we want to add. The minimum is 1 negative categories; the max is 85 - |Cpos| (in this case, we have 85 categories in the prompt in total).

Hope this resolves your question!
